site_name: Tidegate Optimization Tool

theme:
  name: "readthedocs"

extra_css:
  - css/tidegates.css
  
plugins:
  - search
  - mkdocstrings

nav:
  - user.md
  - install.md
  - server.md
  - developer.md
