site_name: Tidegate Optimization Tool

theme:
  name: "readthedocs"

extra_css:
  - css/tidegates.css
  
plugins:
  - search
  - mkdocstrings

nav:
  - "Home":
    - index.md
  - "User Instructions":
    - user.md
  - "Installation":
    - "Install and Configure": install.md
    - data.md
    - server.md
  - "Developer":
    - modules.md
    - "Target Definition": targets.md
    - "Project Data": project.md
    - "Widgets":
      - "Widget Classes": widgets.md
      - "TGMap": map.md
      - "RegionBox": regionbox.md
      - "BudgetBox": budgets.md
      - "TargetBox": targetbox.md
      - "InfoBox": infobox.md
      - "OutputPane": outputpane.md
      - "DownloadPane": downloadpane.md
      - "TideGatesApp": app.md
    - "OP (OptiPass Interface)": optipass.md
    - main.md
    - tests.md
